Models/Clients.cs
using System;
using System.Collections.Generic;

namespace Occupeye.Models
{
    public partial class Clients
    {
        public Clients()
        {
            Sensors = new HashSet<Sensors>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public ICollection<Sensors> Sensors { get; set; }
    }
}

Models/Sensors.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Occupeye.Models
{
    public partial class Sensors
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public int? ClientId { get; set; }
        [Required]
        public string Locale { get; set; }
        public bool Activate { get; set; }
        public bool? Data { get; set; }

        public Clients Client { get; set; }
    }
}

Models/occupeyedbContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Occupeye.Models
{
    public partial class occupeyedbContext : DbContext
    {
        public occupeyedbContext()
        {
        }

        public occupeyedbContext(DbContextOptions<occupeyedbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Sensors> Sensors { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer("Server=localhost;user=user user;password=password;Database=database");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Clients>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(256)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Sensors>(entity =>
            {
                entity.Property(e => e.Locale)
                    .HasMaxLength(256)
                    .IsUnicode(false);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(256)
                    .IsUnicode(false);

                entity.HasOne(d => d.Client)
                    .WithMany(p => p.Sensors)
                    .HasForeignKey(d => d.ClientId)
                    .HasConstraintName("FK__Sensors__Clients__15502E78");
            });
        }
    }
}

Controllers/Api/SensorsApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Occupeye.Models;

namespace Occupeye.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class SensorsApiController : ControllerBase
    {
        private readonly occupeyedbContext _context;

        public SensorsApiController(occupeyedbContext context){
            _context = context;
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> Get(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Sensors model = await _context.Sensors.FirstOrDefaultAsync(m => m.Id == id);
            if (model == null)
            {
                return NotFound();
            }
            return Ok(model);
        } 

        [HttpGet]
        public async Task<IActionResult> Get()
        {
            List<Sensors> model = await _context.Sensors.ToListAsync();
            if (model == null)
            {
                return NotFound();
            }
            return Ok(model);
        } 

        [HttpPost]
        public async Task<IActionResult> Post([FromBody] Sensors value)
        {
         return Ok();
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }  
            Sensors delete = await _context.Sensors.FirstOrDefaultAsync(m => m.Id == id); 

                 _context.Sensors.Remove(delete);
                await _context.SaveChangesAsync();
         return Ok();
        }
    }
}

Controllers/SensorsController.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Occupeye.Models;

namespace Occupeye.Controllers
{
    public class SensorsController : Controller
    {

        public IEnumerable<Sensors> _sensors { get; set; }

        private readonly occupeyedbContext _context;

        public SensorsController(occupeyedbContext context){
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index(){
        using (var client = new HttpClient())
        {
            client.BaseAddress = new Uri("http://localhost:5000/api/sensorsapi/");
            var responseTask = client.GetAsync("");
            responseTask.Wait();
            var result = responseTask.Result;
            if (result.IsSuccessStatusCode)
            {
                var readTask = result.Content.ReadAsAsync<List<Sensors>>();
                readTask.Wait();
                _sensors = readTask.Result;
            }else{
                return View("error no model found");
            }
        }
        return await Task.Run(() => View(_sensors));
        }

        [HttpPost]
        public async Task<IActionResult> Add(Sensors sensors){
            if (ModelState.IsValid)
            {
                
                await _context.Sensors.AddAsync(sensors);
                await _context.SaveChangesAsync();
                return await Task.Run(() => Redirect("Index"));
            }
            else
            {
                return View();
            }
        }
        
        [HttpGet]
        public async Task<IActionResult> Add(){
                    return await Task.Run(() => View());
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id){
		using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("http://localhost:5000/api/sensorsapi/");
                    var deleteTask = client.DeleteAsync(id.ToString());
                    deleteTask.Wait();

                    var result = deleteTask.Result;

                    return await Task.Run(() => RedirectToAction("Index"));
                }
        }
    }
}

Controllers/ValuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Occupeye.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
        // GET api/values
        [HttpGet]
        public ActionResult<IEnumerable<string>> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/values/5
        [HttpGet("{id}")]
        public ActionResult<string> Get(int id)
        {
            return "value";
        }

        // POST api/values
        [HttpPost]
        public void Post([FromBody] string value)
        {
        }

        // PUT api/values/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody] string value)
        {
        }

        // DELETE api/values/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}

Views/Sensors/Add.cshtml
@model Occupeye.Models.Sensors

<div class="container">
    <div class="row pb-5">
        <div id="anchor" class="col">
            @using (Html.BeginForm())
            {
                <div class="form-signin">
                    <h2 class="form-signin-heading"  id="anchor">Sensor Creation</h2>

                    <div>
                        @Html.Label("Name")
                        @Html.TextBoxFor(x => x.Name, new {id = "inputName", @class = "form-control", placeholder = "Name"})
                        @Html.ValidationMessageFor(x => x.Name, null, new {id = "l-Style", style = "color:#FF1C4D"})
                    </div>
                    <div>
                        @Html.Label("Client ID number")
                        @Html.TextBoxFor(x => x.ClientId, new {id = "inputClientId", @class = "form-control", placeholder = "ClientId"})
                        @Html.ValidationMessageFor(x => x.ClientId, null, new {id = "l-Style", style = "color:#FF1C4D"})
                    </div>
                    <div>
                        @Html.Label("Location")
                        @Html.TextBoxFor(x => x.Locale, new {id = "inputLocale", @class = "form-control", placeholder = "Locale"})
                        @Html.ValidationMessageFor(x => x.Locale, null, new {id = "l-Style", style = "color:#FF1C4D"})
                    </div>
                    <div>
                        @Html.Label("Data")
                        @Html.CheckBoxFor(x => x.Activate, new {id = "inputActivate", @class = "form-control", placeholder = "Activate"})

                    </div>
                    <br>
                    <div>
                        <input class="btn btn-lg btn-primary btn-block" type="submit" value="Submit"/>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    <script src="wwwroot/JS/ResponsiveValidation.js"></script>
}

Views/Sensors/Edit.cshtml
@model Occupeye.Models.Sensors

<div class="container">
    <div class="row pb-5">
        <div id="anchor" class="col">
            @using (Html.BeginForm())
            {
                <div class="form-signin">
                    <h2 class="form-signin-heading"  id="anchor">Sensor Edit</h2>

                    <div>
                        @Html.Label("Name")
                        @Html.TextBoxFor(x => x.Name, new {id = "inputName", @class = "form-control", placeholder = "@model.Name"})
                        @Html.ValidationMessageFor(x => x.Name, null, new {id = "l-Style", style = "color:#FF1C4D"})
                    </div>
                    <div>
                        @Html.Label("Client ID number")
                        @Html.TextBoxFor(x => x.ClientId, new {id = "inputClientId", @class = "form-control", placeholder = "@model.ClientId"})
                        @Html.ValidationMessageFor(x => x.ClientId, null, new {id = "l-Style", style = "color:#FF1C4D"})
                    </div>
                    <div>
                        @Html.Label("Location")
                        @Html.TextBoxFor(x => x.Locale, new {id = "inputLocale", @class = "form-control", placeholder = "@model.Locale"})
                        @Html.ValidationMessageFor(x => x.Locale, null, new {id = "l-Style", style = "color:#FF1C4D"})
                    </div>
                    <div>
                        @Html.Label("Data")
                        @Html.CheckBoxFor(x => x.Activate, new {id = "inputActivate", @class = "form-control", placeholder = "@model.Activate"})

                    </div>
                    <br>
                    <div>
                        <input class="btn btn-lg btn-primary btn-block" type="submit" value="Submit"/>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    <script src="wwwroot/JS/ResponsiveValidation.js"></script>
}

Views/Sensors/Index.cshtml
@model List<Occupeye.Models.Sensors>
<div class="container">
    <div class="row pb-5">
        <div id="anchor" class="col">
            <div>
                <a href="@Url.Action("Add", "Sensors")" class="btn btn-lg btn-primary btn-block"> Add </a>
            </div> 
            <br>
            <h2>Sensor list</h2>
            <br>
            @foreach(var item in Model){
                <div>
                    <h5>Sensor: @item.Name</h5>
                    <hr />
                    <div>
                        <h6>
                            Sensor name: @item.Name
                        </h6>
                        <p>
                            Activate available: @item.Activate
                        </p>
                        <p>
                            Client ID: @item.ClientId
                        </p>
                    </div>
                </div>
                <div>
                    @Html.ActionLink("Edit this item","Add", "Sensors") |
                    @Html.ActionLink("Return to list","Index", "Sensors") |
                    @{
                      if(item.Data == null){item.Data = false;}
                      if (item.Data.Value){@Html.ActionLink("Delete","Delete", "Sensors", new{id = @item.Id})}
                    }
                </div>
                <br>
                }

        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="stylesheet" href="~/CSS/bootstrap.css">
    <link rel="stylesheet" href="~/CSS/tether.css">
    <link rel="stylesheet" href="~/CSS/font-awesome.min.css">
    <link rel="stylesheet" href="~/CSS/style.css"/>
    <script src="~/JS/jQuery.js"></script>
    <script src="~/JS/tether.js"></script>
    <script src="/JS/bootstrap.js"></script>
    <title>@ViewBag.title</title>
</head>
<body>
<div class="container">
    <nav class="navbar fixed-top navbar-toggleable navbar-inverse bg-inverse">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#">
            <img src="~/Images/fish.svg" width="30" height="30" class="d-inline-block align-middle" alt="fish">
            Brand
        </a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    @Html.ActionLink("Home", "Index", "Home", null, new {@class = "nav-link"})
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Registration", "RegistrationForm", "Home", null, null, "anchor", null, new {@class = "nav-link"})
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Login", "LoginForm", "Home", null, null, "anchor", null, new {@class = "nav-link"})
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Blog", "Index", "Blog", null, null, "anchor", null, new {@class = "nav-link"})
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Content", "Index", "Vacancies", null, null, "anchor", null, new {@class = "nav-link"})
                </li>
            </ul>
        </div>
    </nav>
</div>

<br />
@RenderBody()
<div id="footer">
    <span id="footertext"> ©2017 Template <a href="#">Legal stuff</a></span>
</div>
@RenderSection("scripts", required: false)
</body>
</html>